services:

  build-es-docs:
    container_name: build-es-docs
    build:
      context: .
    volumes:
      - ./src/assets:/usr/app/src/assets

  elasticsearch:
    container_name: elasticsearch-v8111
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    ports:
      - 9200:9200
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"
      - xpack.security.enabled=false
      - http.port=9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana-v8111
    image: docker.elastic.co/kibana/kibana:8.11.1
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601

volumes:
  es-data: null

